---
title: "Stats Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
In this project, we're using sales data from Safeway Eastern's floral department. This data only shows the flowers/bouqets sold that were bought by Safeway from Intergreen USA. 


```{r cars}
library('plyr')
library('bit64')
library('dplyr')
library('reshape2')
library('ggplot2')

setwd("C:/Users/Holex/Desktop/Stats_Project")

#Sidenote: I saved excel file as a txt before reading it as a table
flower_data <- read.table("flower_data.txt", header = TRUE)

#line below ensures column is date and ordered
flower_data$Txn_Date <- as.Date(flower_data$Txn_Date, format = "%m/%d/%Y")

#Since there are multiple sales on a given day, I want to aggregate the sales based on the date
date_net <- aggregate(Net ~ Txn_Date, flower_data,sum)

plot(date_net$Txn_Date, date_net$Net)

#read in financial data
stock_info <- fread("stockdata.csv")
#change column name so i can do a join
colnames(date_net)[1] <- "Date"
combodata <- join(date_net,stock_info, type="right")
combodata$Volume <- NULL
#plots the closing price and net for a given day
data_m <- melt(combodata,id.vars = "Date")

ggplot(data_m, aes(Date,value, col=variable)) + geom_point() + stat_smooth()

ggplot()


str(data_m)






```

#Testing code here

```{r}
#date_net3 <- aggregate(Net ~ Txn_Date, flower_data,sum)
#date_net3$Txn_Date <- factor(date_net3$Txn_Date, levels =  #date_net3$Txn_Date[order(date_net3$Net)])
#str(date_net3)

#date_net3$Txn_Date <- format(format.Date(date_net3))

#There are also multiple stores, it would be interesting to see how different stores sell based on the day
#link to safeway eastern stores
#https://www.google.com/maps/d/viewer?mid=1SU7aT0QrKqPL-5mGKjwvflXmAz4&hl=en_US&ll=39.02715642805036%2C-76.56616499999996&z=7


store_date_net2 <- aggregate(Net ~ Txn_Date + Store , flower_data, sum)
store_date_net2 <- store_date_net[order(as.Date(store_date_net2$Txn_Date, "%m/%d/%Y")),]


```

```{r}

library('rnoaa')
#https://cran.r-project.org/web/packages/rnoaa/rnoaa.pdf

isd_stations_search(lat=38.901335, lon=-76.980425)

#code to get station name for every longitude and latitude for Safeway Eastern stores


store_locations <- read.table("lat_lng_store.txt", header = TRUE)


coops_search(station_name = 997314, begin_date = 20140928, end_date = 20140929, datum = "stnd", product = "predictions")

ghcnd_search("99999", date_min = "1920-01-01", date_max = "1925-01-01") 

#create a loop that stores dont neeed loop can pass a vector ;)

#meteo_tidy_ghcnd(stationid = "ASN00003003", date_min = "1950-01-01")

station_data <- ghcnd_stations()

meteo_distance(station_data, lat, long, units = "deg", radius = NULL, limit = NULL)
```

You can also embed plots, for example:

```{r pressure, echo=FALSE}

meteo_distance(station_data, 38.901335, -76.98042, units = "deg", radius = NULL, limit = 5)
```

Stock market data
```{r}
library('quantmod')
```

